

DROP TABLE IF EXISTS user;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT  UNIQUE NOT NULL ,
  surname TEXT NOT NULL,
  password TEXT NOT NULL,
  tc INTEGER NOT NULL,
  birim	TEXT NOT NULL,
  doğumtarihi	INTEGER NOT NULL,
  telefon INTEGER NOT NULL,
  eposta TEXT  PRIMARY KEY NOT NULL
);



